# Generated by Django 4.1.3 on 2023-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_adres',
            field=models.CharField(default=0, max_length=200, verbose_name='адрес места'),
            preserve_default=False,
        ),
    ]
