# Generated by Django 4.1.3 on 2023-05-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_place_place_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_pic',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фотка'),
            preserve_default=False,
        ),
    ]
