# Generated by Django 4.1.3 on 2023-05-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_place_place_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотка')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.place')),
            ],
        ),
    ]
